name: Automated browser tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install deps
        run: PUPPETEER_PRODUCT=firefox npm install
      - name: Run tests
        run: npm run test:integration
